# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            PageFault
tagline:          'Security blog'
description:      'Ramblings of a bug-hunter!'
url:              http://pagefault.me
baseurl:          /

author:
  name:           'Sahad NK'
  url:            https://twitter.com/sahad_nk

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sahadnk72/pagefault
