# Permalinks
permalink:        pretty

# Setup
title:            PageFault
tagline:          'Security blog'
description:      'Bug bounty rants | App-sec ramblings'
url:              https://pagefault.me
baseurl:          https://pagefault.me

author:
  name:           'Sahad NK'
  twitter:            https://twitter.com/sahad_nk/
  facebook:           https://facebook.com/sahad.nk.nk/
  linkedin:           https://www.linkedin.com/in/sahadnk/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sahadnk72/pagefault
  
  # Google services
google_analytics: UA-99095981-1
